name: Publish NPM

on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Yarn CLI
        uses: CultureHQ/actions-yarn@v1.0.1
      - name: Install dependencies
        run: yarn install
      - name: Build app
        run: yarn build

  release:
    name: Release
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Yarn CLI
        uses: CultureHQ/actions-yarn@v1.0.1
      - name: Install dependencies
        run: yarn install
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release --no-ci
